### ISSUE TITLE
Tracking: v2.5.2

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#142]
Anterior: #129

# Tema principal: Bluetooth bugs

## Melhorias e Bugfixes
- [x] #83
- [x] #80
- [x] #81
- [x] #152
- [x] #140 
- [x] #119 (implementada; vamos verificar depois do launch antes de dar close)
- [x] #149
- [x] #144

## Débitos Técnicos
- [x] #105
- [x] #41 (continuar)

## Novidades:
```
- Não repete a mesma frase imediatamente (ex.: quando a dupla recusa truco)
- Botões do Bluetooth agora visíveis com o celular deitado (paisagem)
- Corrigido erro quando criador inicia jogo antes do cliente estar pronto
- Ao perder a conexão, celular que entrou no jogo agora mostra mensagem imediatamente
- Corrigidos dois erros que fechavam o aplicativo ao iniciar ou encerrar partida
- Ícone do aplicativo alinhado com versões novas do Android
```

## Ficam para versões futuras
- [ ] #119 (ver se o erro sumiu)
- [ ] #71 (pensar se é uma boa/necessário introduzir isso antes do multiplayer ou de rever as estratégias)
- [ ] #54 (revisitar)
