### ISSUE TITLE
Tracking: v2.5.3

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#158]
Anterior: #142

# Tema principal: placar persistente e diálogo móvel

## Melhorias e Bugfixes
- [x] #119
- [x] #54
- [x] #111
- [x] #109
- [x] #166 

## Débitos Técnicos
- [x] #41 (colocar CI)

## Novidades:
```
- Placar de partidas agora mostra vitórias e derrotas desde que o jogo foi instalado (você pode clicar nele para limpar e/ou configurar para começar em 0x0, como fazia antes).
- Pergunta de truco agora pode ser arrastada (para poder ver as cartas abaixo dela)
- Celular que procura jogo Bluetooth não causa mais erro na partida seguinte ao sair no final de uma partida.
```

## Ficam para versões futuras
- [x] #119 (verificar se resolveu)
- [x] #54 (verificar se resolveu)
- [ ] #41 (outros TODOs)
- [ ] #137 (pelo menos um teste + eliminação dos instanciamentos)
