### ISSUE TITLE
Tracking: v3.0.x

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#173]
Anterior: #158 

# Tema principal: MVP Internet

## Melhorias e Bugfixes
- [x] #171
- [x] #170 
- [x] #175
- [x] #38 

## Débitos Técnicos
- [x] #119 (verificar se resolveu)
- [x] #54 (verificar se resolveu)
- [x] #41 (implementou testes no server)

## Novidades:
```
- JOGO PELA INTERNET (EXPERIMENTAL) com salas públicas (só pessoas, sem bots) e privadas 
- Novo visual da "sala" Bluetooth (mesmo do jogo online)
- Corrige erro ao conectar celulares com nomes inválidos via Bluetooth
```

## Ficam para versões futuras
- [ ] Verificar se resolveu #170, #171 e #172
- [ ] #137 (pelo menos um teste + eliminação dos instanciamentos)
