### ISSUE TITLE
Tracking: v3.0.3

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#217]
Anterior: #173 

# Tema principal: manter pessoas na sala pública e ajustes de UI.

## Melhorias e Bugfixes
- [x] #218
- [x] Desestimula troca de salas e corrige display de espaço e bots #219 

## Novidades:
```
- Facilita formação de salas no multiplayer (orientando quem tenta criar nova sala)
- Corrige display de posições vazias e espaços em nomes
- Indicador visual de que é possível arrastar a caixa de pergunta
```

## Ficam para versões futuras
- [ ] Verificar se resolveu #170, #171 e #172
- [ ] #214 
- [ ] #215 
- [ ] #216 
- [ ] #213
Débito técnico:
- [ ] #137 (pelo menos um teste + eliminação dos instanciamentos)
