### ISSUE TITLE
Tracking: v3.0.4

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#226]
Anterior: #217 

# Tema principal: 
- Trazer mais gente pro online (mas sem derrubar o servidor nem ser chato)

## Melhorias e Bugfixes
- [x] #225

## Débitos Técnicos
- [ ] #137 (pelo menos um teste + eliminação dos instanciamentos)

## Novidades:
```
- Quando uma sala pública na internet está com vagas, o jogo convida pessoas que selecionam o modo daquela sala para completar a mesa.
```

## Ficam para versões futuras
- [ ] Para a 3.0.5, considerar o uso de um [milestone](https://github.com/chesterbr/minitruco-android/milestones) ao invés de uma tracking issue
- [ ] #215 
- [ ] Verificar se resolveu #170, #171 e #172
- [ ] #216 
- [ ] #232
