### ISSUE TITLE
Jogo pela Internet

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#38]
A idéia é migrar o servidor do https://github.com/chesterbr/minitruco-j2me e reimplementar a parte cliente (deve dar pra usar muito das activities Bluetooth).

#34 migrou uma versão inicial do servidor (já permite jogar via telnet com salas públicas) e #177 / #180 / #182 consertaram um monte de coisas. O que ainda falta está segregado abaixo:

### Indispensáveis (não dá pra lançar sem isso)
- [x] Verificar que não é possível entrar na sala quando tem jogo em andamento ou finalizado (internet e bluetooth, mas mais internet mesmo) - o internet tá ok, Bluetooth tem o problema mas tá logado em #187
- [x] Checagem de versão (consolidar com o Bluetooth) #190
- [x] Configurar o SO do servidor para aceitar um número "grande" de conexões (o maior obstáculo era memória; não precisamos de file handles ou qualquer outro recurso a cada novo jogador, e cada um está no máximo em uma sala e uma partida).
- [x] Limitar o no. de jogadores conectados #196
- [x] Permitir consulta fácil de # de jogadores conectados #196
- [x] Configurar o ~fail2ban~ ufw para evitar flood (não é um Cloudfare, é só pra evitar que script kiddies usem o load balancer ou algo tão básico quanto ele): https://github.com/chesterbr/chester-ansible-configs/commit/39b353c91d0e0604169c7badd3a4aed4818f350f
- [x] #183
- [x] Mensagem "Conectando" no cliente internet #197
- [x] Mostrar o botão internet e pedir as permissões adequadas 
- [x] Configurar swapfile no servidor (e também reboot suave em caso de upgrades)
- [x] Rever formato dos logs (#201 e https://github.com/chesterbr/chester-ansible-configs/commit/e42f4e1cf61ef57ae290bd42d4a8ee43c3b0a4ea resolvem quase tudo, falta só a rotation que vai ter que ser no logrotate)
  - [x] algumas coisas vêm formatadas, outras não (talvez elas só sejam coisas multilinha, tipo exceções - nesse caso, seria melhor logar com outro separador de linha pra beneficiar o grep? O que outros sistemas fazem?)
  - [x] algumas vão pra stdout, outras pra stderr (provavelmente é log level, mas de repente nem vale a pena segregar; de repente configurar no supervisord)
  - [x] tem que ter o PID do servidor (pra segregar servidor em shutdown)
  - [x] tem que ter um tempo máximo na rotation (pra ser compliant com GDPR, etc.)
- [x] Atualizar política de coleta de dados (ver se vamos tirar IPs dos logs ou não; ver se devemos avisar que podemos usar os jogos para treinar AI)
- [x] Considerar aumento do tempo do keepalive no servidor (5s talvez seja meio agressivo para conexões ruidosas, e a maior parte dos disconnects vão ser sentidos na hora mesmo) (foi pra 10s em #206)  ~e redução do timeout no cliente (para o jogador não esperar indefinidamente na hora de conectar)~ (esse é só 10s)

### Salas públicas
- [x] Padronizar notificação `I` (server tá `I apelidos posicao modo`, bluetooth tá `I apelidos modo posicao`); incluir tipo de sala (pública, privada ou bluetooth) e código da sala, talvez num campo só pra acomodar o Bluetooth - e talvez as públicas - não ter código de sala, ex.: PUB-A2345, PRI-B2K27, PUB, BLT. #192
- [x] Se o gerente receber notificação de sala pública e cheia, iniciar um countdown e, no fim dele, iniciar o jogo; qualquer notificação I reinicia ou cancela o countdown #193
- [x] Se houverem bots na sala, pedir confirmação quando o gerente clicar em "Jogar"; se jogador estiver sozinho, desligar o botão de jogar. #193
- [x] Exibir tipo de sala (bluetooth/publica/privada)em *todas* as salas (públicas ou privadas) #193
- [x] Mover botões para "controles de gerente" (i.e., deixar claro que o jogador é o gerente); só exibir se for sala privada ou bluetooth #193
- [x] Destacar nome do jogador e quem é o gerente #197
- [x] Considerar se vamos permitir bots no jogo (se não, trocar o código cliente; hoje ele permite até 2 bots na sala) #203

### ~Kick / troca de sala~ Defesa contra abuso
- [x] Botão "Nova Sala pública"; tirar o jogador da sala e mandar o comando de criar sala pra ele
- [x] ~Kick: se for gerente, botar um x no nome de cada jogador. Se clicar e confirmar, manda comando K + posição (internet), ou desconectar (bluetooth). Jogador vai pra nova sala pública (portanto gerente) com alertbox.~ Desisti, vamos acabar com o gerente
- [x] Eliminar o conceito de gerente em sala pública e só iniciar o jogo com ela cheia #203

### Sala privada
- [x] Botão "Nova sala privada" em todos os jogadores internet
- [x] Botão "Entrar com código", mesmo acima 
- [x] Exibir código da sala privada
- [x] Conferir se a implementação de sala privada no servidor está completa; implementar testes

### Geral
- [x] Quando estiver em sala privada, desabilitar botão de criar sala privada e botão de entrar com código (ou ainda: esconder todos os botões; se a pessoa quiser sair, volta pra tela principal)
- [x] Opção "Sempre perguntar o nome ao conectar" #204
- [x] Tratar falha ao entrar na sala corretamente (nem que seja fechando a activity, não pode ficar inconsistente)
- [x] Considerar códigos puramente numéricos (mais fácil de digitar e sanitizar)
- [x] Mais evidência no código
- [x] Mudar a cor da mensagem (ela fica parecendo um botão)
- [x] No cliente, não logar Keepalive
- [x] Não deixar a pessoa se chamar "bot"
- [x] ~Repensar títulos dos botões trocar/inverter~ posso fazer isso no futuro
- [x] Remover `TTFF`das notificações `I`
- [x] Não deixar setar o nome se estiver dentro de uma sala
- [x] #191
- [x] Conferir se o keepalive não está atrapalhando
- [x] Suavizar o " ❌ Erro" na mensagem de desconexão/falha na conexão #197
- [x] #181
- [x] ~Implementar um kill switch do botão~ melhor botar um aviso de que é versão de testes, que os servidores podem sair do ar e fazer a pessoa clicar em "Entendi", ou nem isso
- [x] Mostrar o modo de jogo dentro da sala (e dar linha da barra de status, que é feia e ninguém vê
- [x] ~Considerar trocar os _ por espaços ao exibir o nome do jogador (também teria que trocar ao consultar; talvez seja~  treta a essa altura do campeonato ~)~
- [x] bug: jogadores estão ficando pendurados no servidor; de repente um esquema pra listar todos os jogadores conectados? debugar com VisualVM? #206 via task abaixo (e também listando as threads que resistiram, que agora são nomeadas com o nome inicial do jogador)
- [x] considerar um timeout no shutdown (ex.: se demorar mais que 60 minutos, derruba) #206
- [x] ~considerar um restart mandatório diário (do server e/ou do servidor)~ já vai ter restart quase todo dia por causa de pacote de segurança que foi atualizado; se for preciso colocar isso, é fácil mexer no script do Ansible

**Comment by chesterbr** [comment]
Esses seriam os próximos passos (atualizar lista acima com eles)

- [ ] Ao clicar em Internet, pedir o nome em popup (idealmente antes de conectar, senão depois)
- [ ] Salvar o último nome utilizado
- [ ] Ao entrar, imediatamente dar um `E PUB` e mostrar a sala pública
- [ ] Se usuário for gerente, exibir botões trocar/inverter
- [ ] Implementar/habilitar back-end dos botões trocar/inverter
- [ ] Se sala for pública, exibir botão "Sala Privada"
- [ ] Se sala for privada, exibir código no lugar do botão
- [ ] Botão "Sala Privada" mostra popup "informe código ou deixe em branco para criar nova sala"
- [ ] popup usa o comando de criar/entrar em sala privada
- [ ] implementar/testar back-end de criar/entrar em sala privada

TBD:
- Lógica/UI  do "Quero Jogar"
- Final de jogo
- Se vai permitir criar sala pública do zero (e lógica/UI)
