### ISSUE TITLE
Tracking - 2.4.3

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#88]
# Tema principal: Modos de jogo e Jogador mais inteligente

## Melhorias e Bugfixes
- [x] #45 
- [x] #89
- [x] Rever créditos/copyright (por enquanto não vale a pena mexer)
- [x] #60 
- [x] #86
- [x] #61 (em particular para garantir que as estratégias entendem o tento mineiro)
- [x] #82 
- [x] Arrumar alturas dos botões na tela de título

## Débitos Técnicos
- [x] #87 
- [x] #91 

## Novidades:
```
- Volta da Manilha Velha (clique no "Brasil" para escolher ela ou Baralho Limpo)
- Animações mais fluidas (até 60FPS) e distribuição/recolhimento mais rápidos
- Tela do jogo sem título/menu (= mais espaço para cartas)
- Escolha de cor das cartas (para resolver problemas de modo escuro)
- Bots mais ajustados para o truco mineiro
```

## Ficam para versões futuras
- #37
- #71 
- #66
- #41
