### ISSUE TITLE
Tracking: v2.4.4

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#99]
# Tema principal: TBD

### Médias
- [x] #36
- [x] #85 
- [x] #102

### Pequenas
- [x] #92 
- [x] #39 
- [x] #103

## Débitos Técnicos
- [x] Mostra `MesaView` no editor de layout, com cartas e placares (antes ficava só um vazio verde)

## Novidades:
```
- Sempre mostra quem vai abrir a mão de 10/11
- Placar de partidas ganhas/perdidas
- Alinha todos os placares e marcadores na parte inferior/lateral
- Diversas correções e ajustes visuais nas cartas, balões e diálogos
- Correção de SecurityException em alguns Redmi com versões antigas e bugadas do Android 12
- Usa cor de fundo customizada das cartas nos balões
```

## Ficam para versões futuras
- [ ] #37
- [ ] #71 (provavelmente só Bluetooth)
- [ ] #101
- [ ] #66
- [ ] #83
- [ ] #41 (continuar)
- [ ] #62 
- [ ] documentação do desenvolvedor (buscar ou criar issue)

**Comment by chesterbr** [comment]
Bugs a arrumar:
- [ ] Placar da partida desalinhando quando gira o tablet
- [ ] Gap entre a borda e o diálogo da pergunta
